### ISSUE TITLE
Double escaping url's

### ISSUE THREAD

**Issue by bboughton** [lucaong/jQCloud#26]
Rails url helpers escape special characters when creating urls, so when jQCloud escapes the url it double escapes it.

``` html
<script type="text/javascript" >
  var word_array = [{text: "John's Bday", weight: 1, link: "/posts?tag=John%27s+Bday"}]
</script>
```

Becomes...

``` html
<span id="example_word_1" class="w1">
  <a href="/posts?tag=John%2527s+Bday">John's Bday</a>
</span>
```

Which doesn't link correctly.
### Suggested fix

Adding a boolean option _encode_urls_ that would allow the user to decide

**Comment by platinumjesus** [comment]
Just for other fellow developers that used this excellent library: the library already has an **encodeURI** option that can be set to false/true and it is true by default.
